### PR TITLE
feat: configure patch mode

### LINKED ISSUE #134: Add the possibility to enable Azure-orchestrated patching on the VM module
### Module Name

vm

### Description

Add a new boolean variable to enable Azure-orchestrated patching

### Example Terraform Configuration

```terraform
variable "azure_orchestrated_patching_enabled" {
  description = "Should Azure-orchestrated patching be enabled for this VM?"
  type        = bool
  default     = false
}

locals {
...
patch_mode = var.azure_orchestrated_patching_enabled ? "AutomaticByPlatform" : "ImageDefault"
...
}

{
...
  bypass_platform_safety_checks_on_user_schedule_enabled = var.azure_orchestrated_patching_enabled

  patch_assessment_mode = local.patch_mode
  patch_mode            = local.patch_mode
...
}
```

### PR DESCRIPTION
**Pull request by stiross79**
Fixes equinor/terraform-baseline#134

### CODE REVIEW

**Review by hknutsen — COMMENTED** [review]
I see that `azurerm_windows_virtual_machine` supports more than your two values for `patch_mode`.

Would it be an idea to create a variable `patch_mode` instead and document the allowed values, then set `bypass_platform_safety_checks_on_user_schedule_enabled` based on the value of `patch_mode`?

I think your implementation looks great and I'd prefer it over my suggestion, but I think my suggestion supports more scenarios.

**Comment by stiross79** [comment]
> I see that `azurerm_windows_virtual_machine` supports more than your two values for `patch_mode`.
> 
> Would it be an idea to create a variable `patch_mode` instead and document the allowed values, then set `bypass_platform_safety_checks_on_user_schedule_enabled` based on the value of `patch_mode`?
> 
> I think your implementation looks great and I'd prefer it over my suggestion, but I think my suggestion supports more scenarios.

I will change it, although I can not see a scenario where you would want the assessment to be handled in Azure, but not the patching itself.

**Review by stiross79 — COMMENTED** [review]
Looks good

**Comment by hknutsen** [comment]
Default values set according to recommendations here: https://learn.microsoft.com/en-us/azure/virtual-machines/automatic-vm-guest-patching

@stiross79 do you agree with my changes?

@helenakallekleiv If Stian agrees, could you please give a review?

**Comment by stiross79** [comment]
@hknutsen I do agree that we set defaults following azure recommendations.

**Review by helenakallekleiv — APPROVED** [review]
Looks very good to me and tests are ✔️

**Comment by hknutsen** [comment]
@stiross79 Fire away 🚀

**Pull request merged**
