### PR TITLE
feat: associate network interface with security group

### LINKED ISSUE #32: add nsg_group_id parameter to ip_configurations
We should have the possibility to assign a Network Security Group to network interfaces.

### Variables
```tf
variable "network_interfaces" {
...
    nsg_id = optional(string)
...
}
```

### Main
```tf
resource "azurerm_network_interface_security_group_association" "this" {
  for_each = {
    for k, v in var.network_interfaces : k => v if v.nsg_id != null
  }
  network_interface_id      = azurerm_network_interface.this[each.key]
  network_security_group_id = each.value.nsg_id
}
```

### PR DESCRIPTION
**Pull request by hknutsen**
Closes #32

### CODE REVIEW

**Comment by hknutsen** [comment]
@stiross79 Am I correct in my assumption that only a single NSG can be attached per NIC? 🤔 If yes, I think this PR can be merged as it will ensure only a single NSG association is created per NIC (unless users try to create additional associations outside of this module).

**Comment by stiross79** [comment]
@hknutsen That is correct

**Comment by hknutsen** [comment]
Consider this PR as ready to review then 🙌

**Review by stiross79 — APPROVED** [review]
Looks good.

**Pull request merged**
