### PR TITLE
feat: create virtual machine

### PR DESCRIPTION
**Pull request by hknutsen**
- Implement initial module which creates a simple Linux or Windows VM.
- Implement initial unit tests in the `tests` directory.
- Implement GitHub workflow `.github/workflows/test.yml` that runs unit tests for PRs.
- Implement initial usage examples in the `examples` directory.
- Update `README.md` with short description, development instructions and testing instructions.

### CODE REVIEW

**Comment by sebastianlolv** [comment]
In Windows example, did you set `kind = "Windows"` ? Otherwise looks good 🙂

**Review by stiross79 — DISMISSED** [review]

**Review by sefornes — DISMISSED** [review]
It's a doozy, but it looks okay to me. The basic necessary features are there, and it's well documented. 👍🏻

**Review by vildeaar — DISMISSED** [review]
Looks good to me 👍

**Comment by hknutsen** [comment]
@sebastianlolv Good catch. Will fix and request a review from you.

**Review by sebastianlolv — APPROVED** [review]
LGTM 🙂 🎉

**Pull request merged**
